apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mjrdev/minecraft-server-k8s
        revision: main
        files:
          - path: apps/clients.yaml
  template:
    metadata:
      name: minecraft-{{client}}
    spec:
      project: default
      source:
        repoURL: https://github.com/mjrdev/minecraft-server-k8s
        targetRevision: main
        path: apps/minecraft
        helm:
          values: |
            client:
              name: {{client}}
              port: {{port}}
              port2: {{port2}}
      destination:
        server: https://kubernetes.default.svc
        namespace: minecraft
      syncPolicy:
        automated:
          prune: true
          selfHeal: true