clients:
  - client: cliente-manoel
    port: "30500"
    port2: "30000"
  - client: cliente-robert
    port: "30501"
    port2: "30001"
  - client: cliente-maria
    port: "30502"
    port2: "30002"
  - client: cliente-luis
    port: "30503"
    port2: "30003"
  - client: cliente-wendel
    port: "30504"
    port2: "30004"
  - client: cliente-ana
    port: "30505"
    port2: "30005"
  - client: cliente-joao
    port: "30506"
    port2: "30006"
  - client: cliente-beatriz
    port: "30507"
    port2: "30007"
  - client: cliente-carlos
    port: "30508"
    port2: "30008"
  - client: cliente-fernando
    port: "30509"
    port2: "30009"