clients:
  - client: cliente-945b3565-manoel
    port: "30500"
  - client: cliente-945b3565-robert
    port: "30501"
  - client: cliente-945b3565-maria
    port: "30502"
  - client: cliente-945b3565-luis
    port: "30503"
  - client: cliente-945b3565-wendel
    port: "30504"
