apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-tcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mjrdev/minecraft-server-k8s
    targetRevision: main
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
