apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: nginx-tcp
  ports:
    - name: cliente-a
      port: 43452
      targetPort: 43452
      protocol: TCP
    - name: cliente-b
      port: 43453
      targetPort: 43453
      protocol: TCP
