apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-{{ .Values.client.name }}
  labels:
    app: minecraft-server
    client: {{ .Values.client.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
      client: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: minecraft-server
        client: {{ .Values.client.name }}
    spec:
      nodeSelector:
        nodepool: pool-game-minecraft
        
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "pool-game-minecraft"
          effect: "NoSchedule"
      containers:
        - name: minecraft-server
          image: {{ .Values.imageBedrock }}
          env:
            - name: EULA
              value: "TRUE"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 25565
            - containerPort: 19132
          # readinessProbe:
          #   tcpSocket:
          #     port: 25565
          #   initialDelaySeconds: 115
          #   periodSeconds: 5