apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-{{ .Values.client.name }}
  labels:
    app: minecraft-server
    client: {{ .Values.client.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
      client: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: minecraft-server
        client: {{ .Values.client.name }}
    spec:
      containers:
        - name: minecraft-server
          image: {{ .Values.image }}
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORYSIZE
              value: "2G"
            - name: PAPERMC_FLAGS
              value: "-XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "2"
          ports:
            - containerPort: 25565
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 115
            periodSeconds: 5