apiVersion: v1
kind: Service
metadata:
  name: minecraft-{{ .Values.client.name }}
spec:
  type: ClusterIP
  ports:
    - name: minecraft-java
      port: {{ .Values.client.port }}
      targetPort: 25565
    - name: minecraft-bedrock
      port: {{ .Values.client.port2 }}
      targetPort: 19132
      protocol: UDP
  selector:
    app: minecraft-server
    client: {{ .Values.client.name }}
