apiVersion: v1
kind: Service
metadata:
  name: minecraft-{{ .Values.client.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.client.port }}
      targetPort: 25565
  selector:
    app: minecraft-server
    client: {{ .Values.client.name }}
